### ISSUE TITLE
org/apache/commons/collections4/MapUtils

### ISSUE THREAD

**Issue by cybkw** [alibaba/ARouter#1011]
Caused by: com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.NoClassDefFoundError: org/apache/commons/collections4/MapUtils
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:707)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:786)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:881)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1335)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections4/MapUtils
	at com.alibaba.android.arouter.compiler.processor.BaseProcessor.init(BaseProcessor.java:51)
	at com.alibaba.android.arouter.compiler.processor.AutowiredProcessor.init(AutowiredProcessor.java:58)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.init(incrementalProcessors.kt:41)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.init(annotationProcessing.kt:197)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:686)
	... 40 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections4.MapUtils

As编译无法通过， Android studio chipmunk  | 2021.2.1 patch 1

**Comment by zhi1ong** [comment]
当前 `develop` 已移除 `arouter-compiler` 对 Commons Collections 和 Commons Lang 的运行时依赖，相关工具方法改为项目内实现。该 `NoClassDefFoundError` 对应问题应已由提交 [6b8494a](https://github.com/alibaba/ARouter/commit/6b8494a94947787e35c1cb9d14cec277f9a8100f) 解决。

该 issue 保持打开并标记为 `fixed-awaiting-release`，随 1.5.3 正式发布后关闭。

**Comment by zhi1ong** [comment]
develop 已移除 compiler 对 Commons Collections/Lang 的依赖，相关编译回归通过。修复尚未发布，先关闭此问题。
