### ISSUE TITLE
混淆之后传值报错！！！

### ISSUE THREAD

**Issue by 1025342523** [alibaba/ARouter#1014]
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType        
        at com.alibaba.android.arouter.facade.model.TypeWrapper.<init>(SourceFile:3)
        at com.ysch.healthplatform.ui.main.activity.PersonalInformationActivity$$ARouter$$Autowired$赵.<init>(SourceFile:1)
        at com.ysch.healthplatform.ui.main.activity.PersonalInformationActivity$$ARouter$$Autowired.inject(SourceFile:3)
        at com.alibaba.android.arouter.core.AutowiredServiceImpl.赵(SourceFile:3)
        at com.alibaba.android.arouter.core.AutowiredServiceImpl.autowire(SourceFile:1)
        at 卜.周.秦(SourceFile:2)
        at com.alibaba.android.arouter.launcher.ARouter.inject(SourceFile:1)
        at com.example.fragment.library.base.activity.BaseActivity.onCreate(SourceFile:4)
        at android.app.Activity.performCreate(Activity.java:8086)
        at android.app.Activity.performCreate(Activity.java:8074)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 

Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType        
        at com.alibaba.android.arouter.facade.model.TypeWrapper.<init>(TypeWrapper.java:19)
        at com.ysch.healthplatform.ui.main.activity.PersonalInformationActivity$$ARouter$$Autowired$1.<init>(PersonalInformationActivity.java:22)
        at com.ysch.healthplatform.ui.main.activity.PersonalInformationActivity$$ARouter$$Autowired.inject(PersonalInformationActivity.java:22)
        at com.alibaba.android.arouter.core.AutowiredServiceImpl.doInject(AutowiredServiceImpl.java:49)
        at com.alibaba.android.arouter.core.AutowiredServiceImpl.autowire(AutowiredServiceImpl.java:35)
        at com.alibaba.android.arouter.launcher._ARouter.inject(_ARouter.java:173)
        at com.alibaba.android.arouter.launcher.ARouter.inject(ARouter.java:134)
        at com.example.fragment.library.base.activity.BaseActivity.onCreate(BaseActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:8086)
        at android.app.Activity.performCreate(Activity.java:8074)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by zhi1ong** [comment]
`TypeWrapper` 的泛型信息依赖 class 文件中的 `Signature` 属性；混淆时需要保留官方示例规则中的 `InnerClasses`、`EnclosingMethod` 和 `Signature`，同时保留实现 `ISyringe` 的生成类。该异常属于混淆规则缺失，按已有配置方案关闭。
