### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.server.wm.Task.inPinnedWindowingMode()' on a null object reference

### ISSUE THREAD

**Issue by wypeng2012** [alibaba/ARouter#1039]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.server.wm.Task.inPinnedWindowingMode()' on a null object reference
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3034)
       at android.os.Parcel.createException(Parcel.java:3012)
       at android.os.Parcel.readException(Parcel.java:2995)
       at android.os.Parcel.readException(Parcel.java:2937)
       at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2070)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1840)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1101)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:454)
       at androidx.core.content.ContextCompat$Api16Impl.startActivity(ContextCompat.java:830)
       at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:279)
       at com.alibaba.android.arouter.launcher._ARouter.startActivity(_ARouter.java:449)
       at com.alibaba.android.arouter.launcher._ARouter.access$200(_ARouter.java:45)
       at com.alibaba.android.arouter.launcher._ARouter$3.run(_ARouter.java:391)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)

<img width="429" alt="image" src="https://user-images.githubusercontent.com/4709692/223146582-b8cb3c0d-e464-4a1f-85aa-04585a5de2ca.png">

**Comment by zhi1ong** [comment]
系统进程在 `startActivity` 阶段发生空指针的问题已由 #1048 统一收集复现信息。本 issue 的堆栈同样停留在 Android framework/system_server，合并到主 issue 继续跟踪。
