### ISSUE TITLE
It will caused NullPointException if we implement the interface of 'PretreatmentService' with Kotlin language

### ISSUE THREAD

**Issue by ShenghuaLuo** [alibaba/ARouter#1055]
## Issue
- → Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
                                                                                                    	at com.companyA.moduleB.PretreatmentServiceImpl.onPretreatment(Unknown Source:2)
                                                                                                    	at com.alibaba.android.arouter.launcher._ARouter.navigation(_ARouter.java:286)
                                                                                                    	at com.alibaba.android.arouter.launcher.ARouter.navigation(ARouter.java:186)
                                                                                                    	at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:148)
                                                                                                    	at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:139)
                                                                                                    	at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:130)
                                                                                                    	at com.alibaba.android.arouter.launcher._ARouter.afterInit(_ARouter.java:247)
                                                                                                    	at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:46)
                                                                                                    	at com.greendot.core.router.Router.init(Router.kt:20)
## Version
- → Latest Version 1.5.2

## Case 
- → It will caused NullPointException if we implement the interface of 'PretreatmentService' with Kotlin language and parameter type without '?' like this:
![image](https://github.com/alibaba/ARouter/assets/99248809/24a1399a-52f2-4be1-8b78-820e1ca05819)

## Actually
![image](https://github.com/alibaba/ARouter/assets/99248809/3ca2fce3-e4c4-4833-99a2-50af17c5559b)

## Suggestion ?
1. Whether the parameter 'context' should be removed from interface of 'PretreatmentService' due to it existed at 'init' function ?
2. Or whether the parameter 'context' should be checked before passing ?
    ![image](https://github.com/alibaba/ARouter/assets/99248809/53901309-2bdc-4057-b626-70b516c818da)

##Finally
- →Looking forward to your evaluation and updates

**Comment by zhi1ong** [comment]
已从当前代码路径确认：不显式传入 `Context` 的导航调用会先把空值传给 `PretreatmentService.onPretreatment`，随后才为 `Postcard` 回退到 Application Context，因此 Kotlin 非空参数实现会触发这里的 NPE。

这个问题已纳入 1.5.3，修复需要统一传入预处理服务与实际导航使用的有效 Context，并补充 Java/Kotlin 回归测试。

**Comment by zhi1ong** [comment]
该问题已由 #1084 修复并合并到 `develop`。修复统一了预处理与实际导航使用的有效 Context，并补充了对应的 API 回归测试。现标记为 `fixed-awaiting-release`，Issue 保持打开，待 1.5.3 正式发布后关闭。

**Comment by zhi1ong** [comment]
Fixed on develop: PretreatmentService now receives the effective navigation Context, with Kotlin regression coverage. Not released yet; closing this issue.
