### ISSUE TITLE
Android 14 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by rongkun** [alibaba/ARouter#1061]
异常类型：
java.lang.NoClassDefFoundError
异常信息：
Failed resolution of: Lcom/alibaba/android/arouter/facade/template/IProviderGroup;
异常堆栈：
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alibaba/android/arouter/facade/template/IProviderGroup;
	at dalvik.system.VMRuntime.runHeapTasks(Native Method)
	at java.lang.Daemons$HeapTaskDaemon.runInternal(Daemons.java:687)
	at java.lang.Daemons$Daemon.run(Daemons.java:145)
	at java.lang.Thread.run(Thread.java:1042)
Caused by: java.lang.ClassNotFoundException: com.alibaba.android.arouter.facade.template.IProviderGroup
	... 4 more
java.lang.ClassNotFoundException: com.alibaba.android.arouter.facade.template.IProviderGroup
	at dalvik.system.VMRuntime.runHeapTasks(Native Method)
	at java.lang.Daemons$HeapTaskDaemon.runInternal(Daemons.java:687)
	at java.lang.Daemons$Daemon.run(Daemons.java:145)
	at java.lang.Thread.run(Thread.java:1042)

**Comment by zhi1ong** [comment]
`IProviderGroup` 本身位于 `arouter-api` 中。这个 `NoClassDefFoundError` 更像是最终 APK/split 或运行时 classpath 缺类，现有堆栈还不能证明是 Android 14 专属兼容问题。

请补充：`arouter-api`、`arouter-compiler`、Gradle 插件的准确版本，Gradle dependency tree，Debug/Release 是否都复现，R8/minify、MultiDex、AAB/Dynamic Feature 配置，以及在最终 APK 中是否能找到 `com/alibaba/android/arouter/facade/template/IProviderGroup.class`。最好提供最小复现工程。

该 issue 保持打开并标记为 `needs-repro` 与兼容性问题，拿到打包证据后再定位。

**Comment by zhi1ong** [comment]
IProviderGroup 属于 arouter-api。当前回归包的最终 DEX/R8 检查及 Android 14 运行覆盖未重现该缺类，但不能替代原故障 APK/split 的检查，也不能据此认定原报告已修复。

由于仍缺少故障包中的类定义、依赖树、R8/MultiDex/Dynamic Feature 配置与复现步骤，先关闭此 issue。补充上述证据和准确依赖版本后，可申请重开继续定位。
