### ISSUE TITLE
com.alibaba.android.arouter.launcher._ARouter.startActivity(_ARouter.java:444)报错

### ISSUE THREAD

**Issue by mingzhuzhixing** [alibaba/ARouter#1062]
使用 arouter 1.5.2 有没有遇到这种问题，求指教

android.app.Activity.startActivityForResult(Activity.java:4829) 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:754) 	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:860) 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:249) 	at com.alibaba.android.arouter.launcher._ARouter.startActivity(_ARouter.java:444) 	at com.alibaba.android.arouter.launcher._ARouter.access$200(_ARouter.java:45) 	at com.alibaba.android.arouter.launcher._ARouter$3.run(_ARouter.java:391)

**Comment by zhi1ong** [comment]
现有内容只有 `startActivityForResult` 调用链，没有异常类型、异常消息和 `Caused by`，无法判断是 flag、requestCode、Context、目标 Activity 配置还是系统异常。

请补充完整崩溃头部与根因、导航调用代码、所有 flags/requestCode、设备系统和目标 Activity manifest 配置。该 issue 保持打开并标记 `needs-repro`。

**Comment by zhi1ong** [comment]
当前内容只有 startActivityForResult 的调用栈，没有异常类型、异常消息或完整 cause，无法判断失败原因，也不能确认是否与已处理的 flags 问题相同。

先按缺少必要诊断信息关闭。请补充完整崩溃头部与异常链、导航代码中的 flags/requestCode、Context 和目标 Activity 配置，以及设备系统版本后，再申请重开。
