### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by Heart2009** [alibaba/ARouter#117]
java.lang.ExceptionInInitializerError
	at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:39)
	at com.xxx.service.InitializeService.initArouter(InitializeService.java:60)
	at com.xxx.service.InitializeService.initApplication(InitializeService.java:45)
	at com.xxx.service.InitializeService.onHandleIntent(InitializeService.java:39)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1277)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1200)
	at com.alibaba.android.arouter.thread.DefaultPoolExecutor.<init>(DefaultPoolExecutor.java:50)
	at com.alibaba.android.arouter.thread.DefaultPoolExecutor.getInstance(DefaultPoolExecutor.java:36)
	at com.alibaba.android.arouter.launcher._ARouter.<clinit>(_ARouter.java:51)
	... 8 more

设备信息：android 5.1 (22)，Samsung:GI-I9500_TMMARS:x86

**Comment by zhi1ong** [comment]
信息太少，看不出问题，ARouter.class L39 调用的是 static var
