### ISSUE TITLE
启动目标path时候出现崩溃

### ISSUE THREAD

**Issue by Dwan-xie** [alibaba/ARouter#125]
使用的support-v4版本是23.1.1

```
06-08 17:52:57.971 16841-16841/com.babytree.apps.pregnancy I/ARouter::: ARouter openLog[ ] 
06-08 17:52:57.971 16841-16841/com.babytree.apps.pregnancy I/ARouter::: ARouter openDebug[ ] 
06-08 17:52:57.971 16841-16841/com.babytree.apps.pregnancy I/ARouter::: ARouter printStackTrace[ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=printStackTrace & LineNumber=145 ] 
06-08 17:52:57.971 16841-16841/com.babytree.apps.pregnancy I/ARouter::: ARouter init start.[ThreadId=1 & ThreadName=main & FileName=ARouter.java & ClassName=com.alibaba.android.arouter.launcher.ARouter & MethodName=init & LineNumber=40 ] 
06-08 17:52:57.971 16841-16841/com.babytree.apps.pregnancy E/ARouter: InstantRun support error, com.android.tools.fd.runtime.Paths
06-08 17:52:58.071 16841-16841/com.babytree.apps.pregnancy D/ARouter: Filter 7 classes by packageName <com.alibaba.android.arouter.routes>
06-08 17:52:58.071 16841-16841/com.babytree.apps.pregnancy D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[2], InterceptorIndex[0], ProviderIndex[2][ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=init & LineNumber=82 ] 
06-08 17:52:58.071 16841-16841/com.babytree.apps.pregnancy I/ARouter::: ARouter init success![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=init & LineNumber=62 ] 
06-08 17:52:58.071 16841-16841/com.babytree.apps.pregnancy W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=261 ] 
06-08 17:52:58.071 16841-16841/com.babytree.apps.pregnancy W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=261 ] 
06-08 17:52:58.071 16841-16841/com.babytree.apps.pregnancy D/ARouter::: The group [arouter] starts loading, trigger by [/arouter/service/interceptor][ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=completion & LineNumber=124 ] 
06-08 17:52:58.081 16841-16841/com.babytree.apps.pregnancy D/ARouter::: The group [arouter] has already been loaded, trigger by [/arouter/service/interceptor][ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=completion & LineNumber=132 ] 
06-08 17:52:58.081 16841-16841/com.babytree.apps.pregnancy I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.1][ThreadId=1 & ThreadName=main & FileName=DefaultThreadFactory.java & ClassName=com.alibaba.android.arouter.thread.DefaultThreadFactory & MethodName=newThread & LineNumber=34 ] 
06-08 17:52:58.081 16841-16841/com.babytree.apps.pregnancy I/ARouter::: ARouter init over.[ThreadId=1 & ThreadName=main & FileName=ARouter.java & ClassName=com.alibaba.android.arouter.launcher.ARouter & MethodName=init & LineNumber=47 ] 
06-08 17:53:18.991 16841-16841/com.babytree.apps.pregnancy W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=261 ] 
06-08 17:53:18.991 16841-16841/com.babytree.apps.pregnancy D/ARouter::: The group [login] starts loading, trigger by [/babytree/login][ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=completion & LineNumber=124 ] 
06-08 17:53:18.991 16841-16841/com.babytree.apps.pregnancy D/ARouter::: The group [login] has already been loaded, trigger by [/babytree/login][ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=completion & LineNumber=132 ] 

Caused by: java.lang.NoSuchMethodError: No static method startActivity(Landroid/content/Context;Landroid/content/Intent;Landroid/os/Bundle;)V in class Landroid/support/v4/app/ActivityCompat; or its super classes (declaration of 'android.support.v4.app.ActivityCompat' appears in /data/app/com.babytree.apps.pregnancy-1/base.apk)
at com.alibaba.android.arouter.launcher._ARouter$2.run(_ARouter.java:359)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7237)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by zhi1ong** [comment]
版本问题，自行排查support-v4的版本

**Comment by heliujiang** [comment]
请问怎么解决的呢

**Comment by zhi1ong** [comment]
更新 版本，或者换成和 demo 中相同的版本
