### ISSUE TITLE
当应用切换到后台,过一段时间(大概10分钟)切回来时报错

### ISSUE THREAD

**Issue by jianfeng318** [alibaba/ARouter#177]
如题
当APP切换到后台,大概10分钟左右再切回来(或者直接去应用程序中杀死当前进程),由于app的进程被kill了,报如下错误
`com.alibaba.android.arouter.exception.InitException: ARouter::Init::Invoke init(context) first!
                                                                    at com.alibaba.android.arouter.launcher.ARouter.getInstance(ARouter.java:57)
                                                                    at com.app.haotougu.views.fragments.MyFragment.lambda$initData$0(MyFragment.java:58)
                                                                    at com.app.haotougu.views.fragments.MyFragment$$Lambda$1.accept(Unknown Source)
                                                                    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:59)
                                                                    at com.jakewharton.rxbinding2.view.ViewClickObservable$Listener.onClick(ViewClickObservable.java:39)
                                                                    at android.view.View.performClick(View.java:5207)
                                                                    at android.view.View$PerformClick.run(View.java:21177)
                                                                    at android.os.Handler.handleCallback(Handler.java:742)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)`

麻烦请教一下,有没有api能够检测当前是否init?谢谢

**Comment by zhi1ong** [comment]
不要频繁init，在 Application 中init一次就行
