### ISSUE TITLE
NoSuchMethodError异常

### ISSUE THREAD

**Issue by heliujiang** [alibaba/ARouter#181]
` java.lang.NoSuchMethodError: No static method startActivity(Landroid/content/Context;Landroid/content/Intent;Landroid/os/Bundle;)V in class Landroid/support/v4/app/ActivityCompat; or its super classes (declaration of 'android.support.v4.app.ActivityCompat' appears in /data/app/com.doyiter.casting-1/split_lib_dependencies_apk.apk:classes18.dex)
                                                                         at com.alibaba.android.arouter.launcher._ARouter$2.run(_ARouter.java:359)
                                                                         at android.os.Handler.handleCallback(Handler.java:754)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:160)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6252)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)`

**Comment by heliujiang** [comment]
sorry，`configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '24.1.0'
                }
            }
        }
    }` --> delete
