### ISSUE TITLE
ARouter init logistics center exception! [unable to open DEX file]

### ISSUE THREAD

**Issue by githubliruiyuan** [alibaba/ARouter#185]
com.alibaba.android.arouter.exception.HandlerException:ARouter::ARouter init logistics center exception! [unable to open DEX file]
--
com.alibaba.android.arouter.core.LogisticsCenter.void init(android.content.Context,java.util.concurrent.ThreadPoolExecutor)(SourceFile:85)
com.alibaba.android.arouter.launcher._ARouter.boolean init(android.app.Application)(SourceFile:61)
com.alibaba.android.arouter.launcher.ARouter.void init(android.app.Application)(SourceFile:41)

**Comment by zhi1ong** [comment]
打开 Dex 文件失败，目前我还没遇到过，怀疑是 某非主流 rom 所致，回复下具体机型和系统

**Comment by githubliruiyuan** [comment]
机型              rom
htc         alps/yk858_v20_emmc_tdscdma
OPPO     OPPO/OPPO89T_13039
vivo        vivo/msm8226
Philips    Philips/Philips

**Comment by naturs** [comment]
遇到同样的问题
机型：联想 A800
系统：android 4.0.4 (SDK 版本：15)
CPU：MT6577

**Comment by LeeeYou** [comment]
遇到同样问题，日志如下
```java
1 java.lang.RuntimeException:Unable to create application com.shell.SuperApplication: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [unable to open DEX file]
2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4575)
3 ......
4 Caused by:
5 com.alibaba.android.arouter.exception.HandlerException:ARouter::ARouter init logistics center exception! [unable to open DEX file]
6 com.alibaba.android.arouter.core.LogisticsCenter.init(SourceFile:85)
7 com.alibaba.android.arouter.launcher._ARouter.a(SourceFile:61)
8 com.alibaba.android.arouter.launcher.ARouter.init(SourceFile:41)
9 com.junte.base.MyApplication.onCreate(SourceFile:174)
10 com.shell.SuperApplication.onCreate(SuperApplication.java)
11 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
12 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4572)
13 android.app.ActivityThread.access$1500(ActivityThread.java:155)
14 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
15 android.os.Handler.dispatchMessage(Handler.java:110)
16 android.os.Looper.loop(Looper.java:193)
17 android.app.ActivityThread.main(ActivityThread.java:5323)
18 java.lang.reflect.Method.invokeNative(Native Method)
19 java.lang.reflect.Method.invoke(Method.java:515)
20 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
21 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
22 dalvik.system.NativeStart.main(Native Method)
```

并不是只出现在非主流机型，我们收集到的设备有
三星 SM-A5009  
华为 H30-T00  
KP-MX4   
OPPO 1107  
联想 K30-T

**Comment by x-chf** [comment]
Unable to create application com.duowan.minivideo.SodaApplication: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Providers$$main]
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4694)
                                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:172)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5468)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
                                                                          at dalvik.system.NativeStart.main(Native Method)


现在这个问题有解决的方法吗

**Comment by BLiYing** [comment]
求解答，为什么 在mac os系统中这个库在android8.0系统（无论真机或模拟器）上跑不起啦
8-06 14:25:25.415 5551-5551/com.tepia.reservoir E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tepia.reservoir, PID: 5551
    java.lang.RuntimeException: Unable to create application com.tepia.reservoir.MyApplication: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [No original dex files found for dex location /data/app/com.tepia.reservoir-2d1nHlpnSKwMy-VqCCCing==/split_lib_resources_apk.apk]
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [No original dex files found for dex location /data/app/com.tepia.reservoir-2d1nHlpnSKwMy-VqCCCing==/split_lib_resources_apk.apk]
        at com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:85)
        at com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:61)
        at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41)
        at com.tepia.base.BaseApplication.appInit(BaseApplication.java:43)
        at com.tepia.base.BaseApplication.onCreate(BaseApplication.java:31)
        at com.tepia.reservoir.MyApplication.onCreate(MyApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by hongxialiu** [comment]
> nit.java:676)
> at dalvik.system.NativeStart.main(Native Method)

你好，后面你解决了吗？我这边也报这个错。
