### ISSUE TITLE
 Init provider failed!

### ISSUE THREAD

**Issue by iceyang1989** [alibaba/ARouter#187]
Caused by: com.alibaba.android.arouter.exception.HandlerException: Init provider failed! Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at com.alibaba.android.arouter.core.LogisticsCenter.completion(LogisticsCenter.java:181)
	at com.alibaba.android.arouter.core.LogisticsCenter.completion(LogisticsCenter.java:138)
	at com.alibaba.android.arouter.launcher._ARouter.navigation(_ARouter.java:276)
	at com.alibaba.android.arouter.launcher.ARouter.navigation(ARouter.java:183)
	at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:149)
	at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:140)
	at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:131)
	at com.jcgroup.commonlib.base.BaseApplication.initComponent(BaseApplication.java:75)
	at com.jcgroup.commonlib.base.BaseApplication.onCreate(BaseApplication.java:41)
	at com.jcgroup.ease.module.EaseApplication.onCreate(EaseApplication.java:35)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5155)

**Comment by zhi1ong** [comment]
Init provider failed 是在调用你自己写的 Service 的 init 方法中出现了异常，要排查你自己的代码的

**Comment by tennkou** [comment]
`logger.error(TAG, "Init provider failed!", e);
                            throw new HandlerException("Init provider failed!");`
报错了，却不带上原始错误信息，这个设计有问题啊。增加排查问题的难度。只是打印了原始报错的日志，不好抓到啊
