### ISSUE TITLE
Fragment加上@Route后与Dagger2有冲突。导致dagger报Compoent找不到符号

### ISSUE THREAD

**Issue by BigXiangxy** [alibaba/ARouter#250]
错误：（所有通过Dagger注入ViewComponent的地方都报这个错误，操作仅仅是往一个不相干的Fragment上加上@route注解）
F:\Work\ASWrok\Nayiye\app\src\main\java\com\xx\nayiye\base\view\BaseActivity.java
Error:(7, 36) 错误: 找不到符号
符号:   类 DaggerViewComponent
位置: 程序包 com.xx.nayiye.base.component

BaseActivity代码：（实际上DaggerViewComponent是正常生成了的）
import com.box.alib.view.BaseLifeActivity;
import com.xx.nayiye.base.component.DaggerViewComponent;
import com.xx.nayiye.base.component.ViewComponent;

/**
 * Created by Administrator on 2017/4/27 0027.
 */

public abstract class BaseActivity extends BaseLifeActivity {
    private ViewComponent component;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        inject(getComponent());
    }

    protected abstract void inject(ViewComponent component);

    private ViewComponent getComponent() {
        if (component == null) {
            component = DaggerViewComponent.builder()
                    .lifecycleComponent(getLifeComponent()).build();
        }
        return component;
    }
}
加速注解的Fragment：（实际上都没有使用）

@Route(path = "/test/fragment")
public class MyFragment extends Fragment {
}

Gradle Console日志：
F:\Work\ASWrok\Nayiye\app\src\main\java\com\xx\nayiye\base\view\BaseActivity.java:7: 错误: 找不到符号
import com.xx.nayiye.base.component.DaggerViewComponent;
                                   ^
  符号:   类 DaggerViewComponent
  位置: 程序包 com.xx.nayiye.base.component
F:\Work\ASWrok\Nayiye\app\src\main\java\com\xx\nayiye\base\view\BaseFragment.java:7: 错误: 找不到符号
import com.xx.nayiye.base.component.DaggerViewComponent;
                                   ^
  符号:   类 DaggerViewComponent
  位置: 程序包 com.xx.nayiye.base.component
F:\Work\ASWrok\Nayiye\app\src\main\java\com\xx\nayiye\base\view\BaseTitleActivity.java:7: 错误: 找不到符号
import com.xx.nayiye.base.component.DaggerViewComponent;
                                   ^
  符号:   类 DaggerViewComponent
  位置: 程序包 com.xx.nayiye.base.component
注: ARouter::Compiler >>> AutowiredProcessor init. <<<
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> InterceptorProcessor init. <<<
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> RouteProcessor init. <<<
注: ARouter::Compiler >>> Found routes, start... <<<
注: ARouter::Compiler >>> Found routes, size is 4 <<<
注: ARouter::Compiler >>> Found provider route: com.xx.nayiye.base.http.HttpOldServiceImpl <<<
注: ARouter::Compiler >>> Start categories, group = http, path = /http/oldservice <<<
注: ARouter::Compiler >>> Found provider route: com.xx.nayiye.base.http.HttpServiceImpl <<<
注: ARouter::Compiler >>> Start categories, group = http, path = /http/defservice <<<
注: ARouter::Compiler >>> Found activity route: com.xx.nayiye.view.activity.LoginActivity <<<
注: ARouter::Compiler >>> Start categories, group = app, path = /app/login <<<
错误: ARouter::Compiler An exception is encountered, [null]
      at com.alibaba.android.arouter.compiler.processor.RouteProcessor.routeVerify(RouteProcessor.java:388)
      at com.alibaba.android.arouter.compiler.processor.RouteProcessor.categories(RouteProcessor.java:357)
      at com.alibaba.android.arouter.compiler.processor.RouteProcessor.parseRoutes(RouteProcessor.java:237)
      at com.alibaba.android.arouter.compiler.processor.RouteProcessor.process(RouteProcessor.java:142)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
      at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
      at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
      at com.sun.tools.javac.main.Main.compile(Main.java:523)
      at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
      at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
      at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:49)
      at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
      at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:99)
      at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
      at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
      at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
      at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
      at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
      at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
      at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:198)
      at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:129)
      at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:95)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
      at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
      at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
      at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
      at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
      at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
      at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
      at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
      at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
      at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
      at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
      at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
      at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      at java.lang.Thread.run(Thread.java:745)
4 个错误

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileKFDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by zhi1ong** [comment]
使用最新版本，早期版本不支持获取 Fragment

**Comment by BigXiangxy** [comment]
实在抱歉，忽略了这个问题.浪费你的时间.抱歉...
