### ISSUE TITLE
HandlerException: Init provider failed! Illegal URL: 

### ISSUE THREAD

**Issue by imliujun** [alibaba/ARouter#300]
```java
com.alibaba.android.arouter.exception.HandlerException: Init provider failed! Illegal URL: 
	at com.alibaba.android.arouter.core.LogisticsCenter.completion(LogisticsCenter.java:304)
	at com.alibaba.android.arouter.core.LogisticsCenter.completion(LogisticsCenter.java:261)
	at com.alibaba.android.arouter.launcher._ARouter.navigation(_ARouter.java:258)
	at com.alibaba.android.arouter.launcher.ARouter.navigation(ARouter.java:171)
```

在子线程调用以下代码偶现崩溃
`val api = ARouter.getInstance().navigation(APIService::class.java)`

具体实现：
```kotlin
interface APIService : IProvider, API

@Route(path = "/api/APIService")
class APIServiceImpl : APIService {
    
    lateinit var api: API
    
    override fun init(context: Context?) {
        api = RetrofitUtils.retrofit.create(API::class.java)
    }
}
```

**Comment by imliujun** [comment]
因为异常信息不完整所以以为是本库的bug，实际上是 retrofit 的异常
