### ISSUE TITLE
release包 报:ARouter init logistics center exception! [Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference]

### ISSUE THREAD

**Issue by lichao1991** [alibaba/ARouter#314]
debug的时候 都没问题
后来进行打release包 一点直接报错
具体日志如下

Caused by: com.alibaba.android.arouter.exception.HandlerException: 
ARouter::ARouter init logistics center exception! [Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference]
	at com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:208)
	at com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:61)
	at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41)
	at com.c503.module.common.base.BaseApplication.onCreate(BaseApplication.java:59)
	at com.c503.module.MyApplication.onCreate(MyApplication.java:20)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4743)
	... 8 more

麻烦说下解决思路 关于线上包 关闭     ARouter.openDebug();
            ARouter.openLog(); 都做了

**Comment by lichao1991** [comment]
因为做过版本控制 以前的版本是没有问题 当时用的routerVersion 版本1.2.1.1 这个版本打的release包就没有问题 但是该版本 在自动注入方面 不支持URL 类型

**Comment by lichao1991** [comment]
最后就是将版本降下来就 release打的包就没问题 但是旧版本不支持很多数据类型的传入 这是个麻烦的问题

**Comment by gmfbilu** [comment]
大哥  ，你解决了吗   我也是遇到这个问题

**Comment by lichao1991** [comment]
哈哈哈 并没有 我就是通过降版本 降到1.2.1.1 release包就没问题了

**Comment by lichao1991** [comment]
查到问题所在了，是因为没有配置版本号 在Arouter初始化的时候 会进行版本判断  但是由于没有配置版本号导致读到的vsersionName是null 所以报 java.lang.String.equals(java.lang.Object)' on a null object reference
但是，在debug模式下 是不进行去读取版本号 关键代码 if (ARouter.debuggable() || PackageUtils.isNewVersion(context)) 

以前的版本（1.2.1.1）release包 不配置版本号 也能跑  原因是压根没有进行版本判断

之前太忙没仔细看源码 静下心思来就可以查到问题了，不过这个异常报得日志不够全，应该把全部异常栈信息抛出来 精确定位到代码行 直接catch异常 但是又没有抛全部 要去找到底哪个string字段 null了

**Comment by SunJenry** [comment]
@lichao1991 完美，就是因为没有配置versionName导致的。
