### ISSUE TITLE
如何同时使用FLAG_ACTIVITY_CLEAR_TASK和FLAG_ACTIVITY_NEW_TASK

### ISSUE THREAD

**Issue by everyoung09** [alibaba/ARouter#316]
API中只支持设置一个flag跳转，8.0系统时只设置FLAG_ACTIVITY_CLEAR_TASK没啥问题，但是5.0系统只设置FLAG_ACTIVITY_CLEAR_TASK时会崩溃，提示需要另外加上FLAG_ACTIVITY_NEW_TASK
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:1610)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:348)
at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:141)
at com.alibaba.android.arouter.launcher._ARouter$2.run(_ARouter.java:359)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5951)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)

**Comment by yy941002** [comment]
怎么解决的呢

**Comment by 4332weizi** [comment]
我的也报这个错误

**Comment by fy5220** [comment]
怎么解决的呢

**Comment by fy5220** [comment]
@chris-wu2015 会报错.虽然能运行..最新版本..而且lint检查代码也会报错..

**Comment by chris-wu2015** [comment]
运行报错具体异常是什么？方便贴一下吗？我这边是没有报错的，Lint检查报错是应该Android中的Flag注解只能识别那几个固定的参数，运算后得到的不在它的范围内所以会报，但源码内部也是通过运算来判断有没有某个标识的，所以理论上讲是没有问题的

**Comment by 4332weizi** [comment]
应该是调用navigation没有传入Activity context

**Comment by chris-wu2015** [comment]
建议所有都传context，没传context的时候我这边就遇到一个奇怪的bug，有时候（特别是冷启动之后某种情况下）无法跳转,断点跟代码都正常，最start的时候没有响应，传了context就没这种现象

**Comment by fy5220** [comment]
@chris-wu2015 就只是提示error.可以运行.谢谢啦

**Comment by chris-wu2015** [comment]
不客气，提示error就是上面我说的原因，注解+lint的问题，可以放过的
