### ISSUE TITLE
下载源码，初始化后，运行依赖注入（参照代码）崩溃，报出问题如下，求解答：

### ISSUE THREAD

**Issue by miqigege** [alibaba/ARouter#323]
## Look at here

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.object2Json(java.lang.Object)' on a null object reference
                                                                                      at com.alibaba.android.arouter.facade.Postcard.withObject(Postcard.java:244)
                                                                                      at com.alibaba.android.arouter.demo.MainActivity.onClick(MainActivity.java:147)

**Comment by chenlin8** [comment]
自定义对象需要实现SerializationService。
