### ISSUE TITLE
升级Studio后没有修改案例代码直接运行出现了错误

### ISSUE THREAD

**Issue by MartinDong** [alibaba/ARouter#340]
Android Studio 3.1
Build #AI-173.4670197, built on March 22, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

![image](https://user-images.githubusercontent.com/7735699/38074885-02196306-3363-11e8-9968-aa86a0b031dc.png)

```log

03-29 15:07:18.821 3074-3074/? E/Thermal-daemon: [charger_ic] temp_new :37  temp_old :36
    Report temperature: [charger_ic] temp :37  report_threshold:1
03-29 15:07:18.822 3074-3074/? E/Thermal-daemon: [ap] temp_new :38  temp_old :37
    Report temperature: [ap] temp :38  report_threshold:1
03-29 15:07:19.647 3623-4085/? E/WifiConfigStore: updateConfiguration freq=5805 BSSID=60:45:cb:65:95:4c RSSI=-59 "tech_5G@4F"WPA_PSK
03-29 15:07:20.914 29884-29884/com.alibaba.android.arouter.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.alibaba.android.arouter.demo, PID: 29884
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
        at android.view.View.performClick(View.java:5264)
        at android.view.View$PerformClick.run(View.java:21297)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5621)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
        at android.view.View.performClick(View.java:5264) 
        at android.view.View$PerformClick.run(View.java:21297) 
        at android.os.Handler.handleCallback(Handler.java:743) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5621) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.object2Json(java.lang.Object)' on a null object reference
        at com.alibaba.android.arouter.facade.Postcard.withObject(Postcard.java:244)
        at com.alibaba.android.arouter.demo.MainActivity.onClick(MainActivity.java:147)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
        at android.view.View.performClick(View.java:5264) 
        at android.view.View$PerformClick.run(View.java:21297) 
        at android.os.Handler.handleCallback(Handler.java:743) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5621) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
03-29 15:07:20.944 3623-3667/? E/ReportTools: This is not beta user build
```

**Comment by zhi1ong** [comment]
没实现序列化的 service
