### ISSUE TITLE
官方demo 点击获取fragment  崩溃

### ISSUE THREAD

**Issue by ChinaTengFei** [alibaba/ARouter#352]
04-17 22:40:11.833 21488-21559/com.alibaba.android.arouter.demo E/test: 位于moudle1中的拦截器初始化了
04-17 22:40:17.092 21488-21533/com.alibaba.android.arouter.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f70ae69a0
04-17 22:40:17.235 21488-21488/com.alibaba.android.arouter.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.alibaba.android.arouter.demo, PID: 21488
                                                                                  java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                                      at android.view.View.performClick(View.java:5275)
                                                                                      at android.view.View$PerformClick.run(View.java:21559)
                                                                                      at android.os.Handler.handleCallback(Handler.java:815)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                      at android.os.Looper.loop(Looper.java:207)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5837)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
                                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                                      at android.view.View.performClick(View.java:5275) 
                                                                                      at android.view.View$PerformClick.run(View.java:21559) 
                                                                                      at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                      at android.os.Looper.loop(Looper.java:207) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5837) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.support.v4.app.Fragment.toString()' on a null object reference
                                                                                      at com.alibaba.android.arouter.demo.MainActivity.onClick(MainActivity.java:207)
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                                      at android.view.View.performClick(View.java:5275) 
                                                                                      at android.view.View$PerformClick.run(View.java:21559) 
                                                                                      at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                      at android.os.Looper.loop(Looper.java:207) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5837) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by ChinaTengFei** [comment]
点其他的都可以

**Comment by xwc520** [comment]
Demo中点击获取fragment  崩溃！！！

**Comment by yxf0448** [comment]
我的demo点击所有的都崩溃，小米8，miui10.3
