### ISSUE TITLE
同一套代码window下用的arouter就没事，Mac直接报错

### ISSUE THREAD

**Issue by liuyangqiao** [alibaba/ARouter#386]
## Look at here
05-28 02:20:38.796 15732-15732/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.administrator.componentsdemo, PID: 15732
    java.lang.RuntimeException: Unable to create application com.example.administrator.componentsdemo.App: **com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [No original dex files found for dex location /data/app/com.example.administrator.componentsdemo-y7W7bRAuohqnRVL4iMNNNw==/split_lib_resources_apk.apk]**
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     **Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [No original dex files found for dex location /data/app/com.example.administrator.componentsdemo-y7W7bRAuohqnRVL4iMNNNw==/split_lib_resources_apk.apk]**
        at com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:85)
        at com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:60)
        at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41)
        at com.example.administrator.componentsdemo.App.onCreate(App.java:15)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by zhi1ong** [comment]
ARouter 就是用 Macbook 开发的。。。

**Comment by liuyangqiao** [comment]
什么系统不重要，那个报错是什么问题呢？

**Comment by zhi1ong** [comment]
看起来是因为 InstantRun，初始化之前 openDebu()

**Comment by zksyp** [comment]
初始化之前，openDebug()一样回报这个错误，我的 gradle版本是3.1.3

**Comment by zhi1ong** [comment]
看你的错误提示是因为找不到 dex 文件，用 arouter-register 插件试试

**Comment by hexl1231** [comment]
关闭instan run 就好了.

**Comment by BLiYing** [comment]
同样遇到这个问题（windows上好好地），为什么在macos系统中关闭android studio的instant run就好了呢?抽风吧

**Comment by sungerk** [comment]
+10086
