### ISSUE TITLE
E/ARouter: Scan map file in dex files made error.

### ISSUE THREAD

**Issue by xialonghua** [alibaba/ARouter#394]
按照步骤来的。报错
E/ARouter: Scan map file in dex files made error.
 java.io.IOException: No original dex files found for dex location /data/app/com.example.yue.architecture-qOd49w0sGDiq7GMrrMdmQA==/split_lib_resources_apk.apk
               at dalvik.system.DexFile.openDexFileNative(Native Method)
               at dalvik.system.DexFile.openDexFile(DexFile.java:353)
               at dalvik.system.DexFile.<init>(DexFile.java:100)
               at dalvik.system.DexFile.<init>(DexFile.java:86)
               at com.alibaba.android.arouter.utils.ClassUtils$1.run(ClassUtils.java:77)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
               at java.lang.Thread.run(Thread.java:764)

**Comment by zhi1ong** [comment]
InstantRun 的情况下，要 openDebug()

**Comment by andvip** [comment]
com.android.tools.build:gradle 3.1.2 会报log 这个错误，3.0.1 就不会，

**Comment by liuyangqiao** [comment]
@andvip 多谢

**Comment by zhi1ong** [comment]
@liuyangqiao  应该是 InstantRun 兼容问题，不过这个只是在开发中生效，可以用 arouter-register, 我抽时间 fix 一下

**Comment by Xiaobin0609** [comment]
请问这个问题fix了吗，我用的gradle 3.1.3的， openDebug()，还是会报错

**Comment by AnyLifeZLB** [comment]
我也遇到了，组件化的时候Manifest文件中的package Name  和   build.gradle 文件中applicationId 不一致出现了，改为一样就好了，不知大家是否和我一样。

**Comment by q947721485** [comment]
目前好像还没有fix，请问这个问题会影响功能使用吗？

**Comment by zhi1ong** [comment]
看起来和包名有关系，断点调试一下，ARouter 扫描 dex 的逻辑

**Comment by junchenChow** [comment]
请问大佬 E/ARouter: Scan map file in dex files made error. 这个问题不管了吗。。

**Comment by LiChangXing** [comment]
遇到同样问题！

**Comment by LiChangXing** [comment]
我把APP  从后台主动销毁后  就一直崩溃    发现原因就是开启了 Instant Run，把Instant run关闭后 好了， 
 不过 我又开启了Instant run 只要不主动杀死进程  就不会崩溃   请大佬看下~

**Comment by BLiYing** [comment]
升级到gradle4.6,android studio3.2.1后有这个错，但是并未崩溃，也不影响使用，就是看着不舒服。

**Comment by ding33211** [comment]
同上，请问最新版本解决了么
