### ISSUE TITLE
三星I9500初始化报错

### ISSUE THREAD

**Issue by zjxuzhj** [alibaba/ARouter#402]
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:39)
       at com.taketours.main.TakeToursApplication.onCreate(TakeToursApplication.java:49)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4562)
       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5263)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Caused by java.lang.IllegalArgumentException
       at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1277)
       at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1200)
       at com.alibaba.android.arouter.thread.DefaultPoolExecutor.<init>(DefaultPoolExecutor.java:50)
       at com.alibaba.android.arouter.thread.DefaultPoolExecutor.getInstance(DefaultPoolExecutor.java:36)
       at com.alibaba.android.arouter.launcher._ARouter.<clinit>(_ARouter.java:51)
       at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:39)
       at com.taketours.main.TakeToursApplication.onCreate(TakeToursApplication.java:49)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4562)
       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5263)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

#228 #203 #117 
应该和这三个issue是同样的情况，请问有什么办法可以修复该机型下的错误。

**Comment by zhi1ong** [comment]
太早期的手机了，调用 setExcutor 使用自己提供的线程池吧，可能是改过 Framework
