### ISSUE TITLE
Multiple dex files define Lcom/alibaba/android/arouter/facade/annotation/Autowired

### ISSUE THREAD

**Issue by misakuo** [alibaba/ARouter#420]
尝试编译项目自带demo的时候出错
Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/facade/annotation/Autowired;
Message{kind=ERROR, text=Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/facade/annotation/Autowired;, sources=[Unknown source file], original message=UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/facade/annotation/Autowired;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
, tool name=Optional.of(Dex)}

AndroidStudio 3.1.2

**Comment by hloong** [comment]
![image](https://user-images.githubusercontent.com/3353954/43557672-5a30383e-9638-11e8-99ee-2e4481fa250b.png)
我也是，运行项目就提示错误
AndroidStudio 3.1.3

**Comment by LiChangXing** [comment]
怎么解决的？
