### ISSUE TITLE
运行时隐藏bug，导致app无法再启动

### ISSUE THREAD

**Issue by smartniu** [alibaba/ARouter#437]
APP正常运行一段时间后，未知原因下APP无法启动，一直cash。报错信息见下：
Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Providers$$appcommon]
                                                       at com.alibaba.android.arouter.core.c.a(LogisticsCenter.java:208)
                                                       at com.alibaba.android.arouter.a.b.a(_ARouter.java:61)
                                                       at com.alibaba.android.arouter.a.a.a(ARouter.java:41)
                                                       at com.md.commonbusiness.route.b.a(**RouterManager.java:32**)
                                                       at com.allinpay.tonglianqianbao.activity.base.AipApplication.onCreate(**AipApplication.java:22**)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4467)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:140) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5143) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
                                                       at dalvik.system.NativeStart.main(Native Method) 

**RouterManager.java:32**行代码为：ARouter.init(application);
**AipApplication.java:22**行代码为：RouterManager.initRouter(Constant.IS_DEBUG, this);
报错是在aroute的init时，init是在application的onCreate中。

注：我通过系统设置中，强制停止app后，再启动app是可以正常启动。
希望尽快查找原因，这是一个隐藏的bug，一旦出现将会是致命的。

**Comment by zhi1ong** [comment]
可以 attach 到 app 上进行调试，未遇到过该问题

**Comment by smartniu** [comment]
我无法再重现了，但是问题确实出现了一次。

**Comment by 494293346** [comment]
我出现了好几次， 概率很高， 请问 ， 有解吗

**Comment by hongxialiu** [comment]
> 我无法再重现了，但是问题确实出现了一次。

你好，后面线上有遇到过吗？

**Comment by hongxialiu** [comment]
> 我出现了好几次， 概率很高， 请问 ， 有解吗

你好，后面解决了吗？
