### ISSUE TITLE
配置成功，可以实现跳转，但是携带实体类的时候不成功，会报空指针

### ISSUE THREAD

**Issue by chuanzhiben** [alibaba/ARouter#442]
所有版本都是最新的
compile 'com.alibaba:arouter-api:1.3.1'
compile 'com.alibaba:arouter-annotation:1.0.4'
annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'

跳转只传字符串是可以的但是若带上实体类会报错
实体类：
public class Test {
    public String name;
    public String positon;

    public Test() {
    }

    public Test(String name, String positon) {
        this.name = name;
        this.positon = positon;
    }
}
参数传递：
 Test test = new Test("jgjggjgjjgjgjgjgjgjg","价格空间更加个公交卡公交公交个就");
            ARouter.getInstance().build("/hhh/hh")
                    .withString("str","jgkjkgjgjgjgj")
            .withObject("object",test)//这里会报错
            .navigation();
报错内容：
AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: cw.cs.myapplication, PID: 1015
                                                                   java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.object2Json(java.lang.Object)' on a null object reference
                                                                       at com.alibaba.android.arouter.facade.Postcard.withObject(Postcard.java:244)
                                                                       at cw.cs.myapplication.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:23)
                                                                       at cw.cs.myapplication.MainActivity$$Lambda$0.onClick(Unknown Source)
                                                                       at android.view.View.performClick(View.java:5280)
                                                                       at android.view.View$PerformClick.run(View.java:21775)
                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                       at android.os.Looper.loop(Looper.java:207)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5975)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                       at _com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)[](url)_

**Comment by zhi1ong** [comment]
这种情况会有保存信息的，传递对象的情况，需要自行实现 SerializationService ，不然 ARouter 不知道应该用什么方式对对象进行序列化
