### ISSUE TITLE
线上环境个别用户通过ARouter调用service出现空指针

### ISSUE THREAD

**Issue by yan269954107** [alibaba/ARouter#452]
在application的onCreate中调用
if (shouldInit()) {//多个进程只调用一次
    ARouter.init(this);
}
然后在Activity中调用服务是空指针ARouter.getInstance().navigation(xxxxx.class).xxx()
很奇怪的是每天几十万的启动次数只有几次到十几次的错误，测试环境还没发现，而且机型Android版本也很分散，从6.0到8.1.0都有。
也看了一下启动过程((IProviderGroup) (Class.forName(className).getConstructor().newInstance())).loadInto(Warehouse.providersIndex)这些服务也都在主线程注册进去了。百思不得其解，难道是shouldInit()这个判断没有进去？但可能性很小，因为这个方法已经用了很多个版本了。
想问下有遇到类似情况的吗？有什么解决思路吗？
目前想到的只有把初始化拿到shouldInit外面试下

java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.xxx.router.service.AccountService.a()' on a null object reference
	at com.xxx.xxx.file.a.a(SourceFile:50)
	at com.xxx.xxx.file.a.onEvent(SourceFile:43)
	at com.xxx.xxx.xxx.login.LoginActivity.clickNewUser(SourceFile:576)
	at com.xxx.xxx.xxx.login.LoginActivity_ViewBinding$2.doClick(SourceFile:146)
	at butterknife.internal.DebouncingOnClickListener.onClick(SourceFile:21)
	at android.view.View.performClick(View.java:5377)
	at android.view.View$PerformClick.run(View.java:21801)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6027)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)

**Comment by zhi1ong** [comment]
这种情况只能多打印日志调试了，偶发不容易复现，ARouter 的逻辑是比较清晰的，多埋点日志进去
