### ISSUE TITLE
ARouter.init anr

### ISSUE THREAD

**Issue by wangzt** [alibaba/ARouter#494]
ARouter.init在Application的onCreate中调用，在小米4上会导致ANR。但是如果把这个初始化放到子线程中去做，在getInstance时又可能会没有初始化完，请问，这种问题，有没有好的方法处理?

**Comment by wangzt** [comment]
小米4 android 4.4.4

"main" prio=5 tid=1 WAIT
  | group="main" sCount=1 dsCount=0 obj=0x41de6e58 self=0x41dd58b0
  | sysTid=16349 nice=0 sched=0/0 cgrp=apps/bg_non_interactive handle=1074782548
  | state=S schedstat=( 357957506 85993907 522 ) utm=22 stm=13 core=3
  at java.lang.Object.wait(Native Method)
  - waiting on <0x41de6f28> (a java.lang.VMThread) held by tid=1 (main)
  at java.lang.Thread.parkFor(Thread.java:1205)
  at sun.misc.Unsafe.park(Unsafe.java:325)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:813)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:973)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:202)
  at com.alibaba.android.arouter.utils.ClassUtils.getFileNameByPackageName(SourceFile:103)
  at com.alibaba.android.arouter.core.LogisticsCenter.init(SourceFile:170)
  at com.alibaba.android.arouter.launcher._ARouter.init(SourceFile:61)
  at com.alibaba.android.arouter.launcher.ARouter.init(SourceFile:41)

**Comment by zhi1ong** [comment]
太老的机型？这个初始化时间很短的，而且有缓存

**Comment by Android500** [comment]
效率太低了，我也是一样的遇到这个问题
