### ISSUE TITLE
navigation()返回null问题

### ISSUE THREAD

**Issue by 751496032** [alibaba/ARouter#543]
Object navigation = ARouter.getInstance().build(ARouterPath.APP_MAIN_ACTIVITY).navigation();

上面返回navigation是null，每个module都有依赖annotationProcessor，不知道是不是与分包有关系，会报错：
2018-11-05 17:51:01.928 5156-5200/? E/ARouter: Scan map file in dex files made error.
    java.io.IOException: No original dex files found for dex location /data/app/com.im.client-qsQAeI33qtMYU4mMmnhAng==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:86)
        at com.alibaba.android.arouter.utils.ClassUtils$1.run(ClassUtils.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)

**Comment by zhi1ong** [comment]
debug 的时候把，要开 openDebug, 不然不会扫描 splitApk
