### ISSUE TITLE
组件化子module注册路由后再次编译运行找不到相关类

### ISSUE THREAD

**Issue by zwonb** [alibaba/ARouter#576]
项目组件化，子module中的一个类第一次编译运行是正常的，安装后打开app没什么问题，然后在这个类中修改了一点小东西，再次编译，编译通过没什么问题，安装后打开app发现找不到此类。
"com.alibaba:arouter-api:1.4.1",
"com.alibaba:arouter-compiler:1.2.2",
报错信息：
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yidont/hr/StaffInfoMainUIF;
        at com.alibaba.android.arouter.routes.ARouter$$Group$$hr.loadInto(ARouter$$Group$$hr.java:16)
        at com.alibaba.android.arouter.core.LogisticsCenter.completion(LogisticsCenter.java:251)
        at com.alibaba.android.arouter.launcher._ARouter.navigation(_ARouter.java:280)
        at com.alibaba.android.arouter.launcher.ARouter.navigation(ARouter.java:184)
        at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:146)
        at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:137)
        at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:128)
        at com.yidont.appmodule.MainUIA.onCreate(MainUIA.kt:48)
        at android.app.Activity.performCreate(Activity.java:6300)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2750)
        at android.app.ActivityThread.-wrap13(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5975)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yidont.hr.StaffInfoMainUIF" on path: DexPathList[[zip file "/data/app/org.yidont.office1-1/base.apk", zip file "/data/app/org.yidont.office1-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.yidont.office1-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.yidont.office1-1/lib/arm64, /data/app/org.yidont.office1-1/base.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/org.yidont.office1-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.alibaba.android.arouter.routes.ARouter$$Group$$hr.loadInto(ARouter$$Group$$hr.java:16) 
        at com.alibaba.android.arouter.core.LogisticsCenter.completion(LogisticsCenter.java:251) 
        at com.alibaba.android.arouter.launcher._ARouter.navigation(_ARouter.java:280) 
        at com.alibaba.android.arouter.launcher.ARouter.navigation(ARouter.java:184) 
        at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:146) 
        at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:137) 
        at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:128) 
        at com.yidont.appmodule.MainUIA.onCreate(MainUIA.kt:48) 
        at android.app.Activity.performCreate(Activity.java:6300) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2750) 
        at android.app.ActivityThread.-wrap13(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5975) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.yidont.hr.StaffInfoMainUIF" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)`

**Comment by zwonb** [comment]
我把build文件删除后，重新编译安装打开又是正常的！

**Comment by zhi1ong** [comment]
路由表缓存了呗，但是你原来的 class 改了，这种情况很少， Clean 就好了
