### ISSUE TITLE
ARouter init logistics center exception

### ISSUE THREAD

**Issue by GavinTvs** [alibaba/ARouter#581]
java.lang.RuntimeException: Unable to create application com.goks.app.application.AppApplication: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Root$$module_trans]
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Root$$module_trans]
        at com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:208)
        at com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:62)
        at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41)
        at com.goks.core.CoreInitLogic.initARouter(CoreInitLogic.java:40)
        at com.goks.core.CoreInitLogic.onCreate(CoreInitLogic.java:27)
        at com.goks.core.application.CoreBaseApplication.logicCreate(CoreBaseApplication.java:42)
        at com.goks.core.application.CoreBaseApplication.onCreate(CoreBaseApplication.java:27)
        at com.goks.app.application.AppApplication.onCreate(AppApplication.java:31)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

问题场景描述：
切换BuildTypes为release时发生错误，debug模式下不会出现该错误。
``` grovvy
buildTypes {
        debug {
            resValue "string", "app_url_host", "http://test-gateway.goks.tv"
        }

        release {
            zipAlignEnabled true
            debuggable false
            signingConfig signingConfigs.release
            resValue "string", "app_url_host", "http://micro-api.goks.tv"

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
报错的模块在settting.gradle并没有引用（需求原因暂时不开发那个模块[module_trans]）

**Comment by 494293346** [comment]
请问是否有解？我也遇到了这个错误

**Comment by zhi1ong** [comment]
应该和混淆有关系，debug 没有 release 才有

**Comment by hongxialiu** [comment]
我也碰到。好像和混淆没有关系。

**Comment by hongxialiu** [comment]
android 4.2版本必现。debug模式下，先在settting.gradle引用。安装运行正常。然后在settting.gradle里面去除该模块引用，覆盖安装点击运行。必蹦

**Comment by Hongyantianhsu** [comment]
1.确定混淆文件没问题
2.手动删除 ARouter$$Root$$module_trans
3.打release包时先不要屏蔽 ARouter.openDebug()
ARouter.openDebug()貌似跟映射表的生成有关，只要映射生成了，就可以关掉Arouter.openDebug()
