### ISSUE TITLE
ARouter::ARouter init logistics center exception

### ISSUE THREAD

**Issue by LiuDongCai** [alibaba/ARouter#593]
java.lang.RuntimeException: Unable to create application com.addcn.android.house591.base.BaseApplication: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [Package manager has died]
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
	at android.app.ActivityThread.access$1300(ActivityThread.java:148)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5189)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [Package manager has died]
	at com.alibaba.android.arouter.core.LogisticsCenter.init(SourceFile:208)
	at com.alibaba.android.arouter.launcher._ARouter.a(SourceFile:62)
	at com.alibaba.android.arouter.launcher.ARouter.init(SourceFile:41)
	at com.addcn.android.house591.base.BaseApplication.onCreate(SourceFile:126)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4531)
	... 10 more

联想 Lenovo K900 4.2.2 机型产生

**Comment by weiweiiapps** [comment]
In my case Setting > Build, Execution, Deployment > Instant run

Uncheck "Enable Instant Run to hot swap code/resource changes on deploy"

Worked Fine.
