### ISSUE TITLE
使用BottomNavigationView+viewpager 加载模块中的fragmnet 出现问题  如何解决呢

### ISSUE THREAD

**Issue by liulangzhe-zen** [alibaba/ARouter#648]
Process: com.liulangzhe.opensourcedome, PID: 28713
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at androidx.fragment.app.BackStackRecord.doAddOp(BackStackRecord.java:396)
        at androidx.fragment.app.BackStackRecord.add(BackStackRecord.java:391)
        at androidx.fragment.app.FragmentPagerAdapter.instantiateItem(FragmentPagerAdapter.java:107)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:23223)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:737)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2782)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1635)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1919)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1523)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7395)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
        at android.view.Choreographer.doCallbacks(Choreographer.java:877)
        at android.view.Choreographer.doFrame(Choreographer.java:808)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by liulangzhe-zen** [comment]
private Fragment HomeFragment = ARouterUtils.getFragment(ARouterConfig.LIULANGZEN_MAIN_FRAGMENT);


 public static BaseFragment getFragment(String path) {     //fragment 也尝试过
        return (BaseFragment) ARouter.getInstance()
                .build(path)
                .navigation();
    }

请问这种如何进行解决

**Comment by fangbicheng** [comment]
请问这个问题是怎么解决的呢？

**Comment by chocozhao** [comment]
请问解决了嘛？
