### ISSUE TITLE
com.alibaba.android.arouter.exception.HandlerException

### ISSUE THREAD

**Issue by zhoufuqiang15** [alibaba/ARouter#712]
项目线上Android 4.4的机型在初始化ARouteR的时候抛出异常闪退,日志如下
java.lang.RuntimeException: Unable to create application com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [unable to open DEX file]
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4708)
	at android.app.ActivityThread.access$1500(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:229)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
Caused by : com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [unable to open DEX file]
	com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:85)
	com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:61)
	com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41)
	me.suncloud.marrymemo.HLJCustomerApplicationLike.initARouter(HLJCustomerApplicationLike.java:276)
	me.suncloud.marrymemo.HLJCustomerApplicationLike.onCreate(HLJCustomerApplicationLike.java:111)
	com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:180)
	android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
	android.app.ActivityThread.handleBindApplication(ActivityThread.java:4705)

**Comment by zhi1ong** [comment]
‘unable to open DEX file ' 感觉和加固有关系，19 年还有 4.4 呢

**Comment by zhoufuqiang15** [comment]
有什么解决方案吗？线上还存在着这个闪退
