### ISSUE TITLE
[ARouter::Compiler >>> Found unsupported class type

### ISSUE THREAD

**Issue by lu-xu** [alibaba/ARouter#713]
e: 错误: ARouter::Compiler An exception is encountered, [ARouter::Compiler >>> Found unsupported class type, type = [com.sun.tools.javac.model.JavacTypes@1435577b].]
      at com.alibaba.android.arouter.compiler.processor.RouteProcessor.parseRoutes(RouteProcessor.java:269)
      at com.alibaba.android.arouter.compiler.processor.RouteProcessor.process(RouteProcessor.java:167)
      at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
      at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:132)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
      at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
      at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
      at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:80)
      at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:36)
      at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:223)
      at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:187)
      at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:98)
      at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:95)
      at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:105)
      at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:80)
      at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:398)
      at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:65)
      at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
      at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:389)
      at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:118)
      at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:166)
      at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:56)
      at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
      at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
      at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
      at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:442)
      at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:102)
      at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1005)
      at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:102)
      at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:138)
      at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1047)
      at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1004)
      at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:441)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
      at sun.rmi.transport.Transport$1.run(Transport.java:200)
      at sun.rmi.transport.Transport$1.run(Transport.java:197)
      at java.security.AccessController.doPrivileged(Native Method)
      at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
      at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
      at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
      at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
      at java.security.AccessController.doPrivileged(Native Method)
      at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)

**Comment by lu-xu** [comment]
前面确实有人提过这个issue，但是并没有解决实际问题。这个也是Android P适配中出现的，麻烦各位大佬给看下

**Comment by daleiyinsi** [comment]
我也遇到这个问题了，始终无法解决

**Comment by ooftf** [comment]
应该是   接口没有继承IProvider导致的

**Comment by lu-xu** [comment]
> 应该是 接口没有继承IProvider导致的

麻烦能说的具体一点吗，我代码里用到接口的地方我看有继承了Iprovider
interface IBuildConfigProvider :IProvider{

**Comment by lu-xu** [comment]
https://github.com/fiji/javac/blob/master/src/main/java/com/sun/tools/javac/model/JavacTypes.java
上面是报错对应的类，
下面是arouter源码里报错对应的类
https://github.com/alibaba/ARouter/blob/master/arouter-compiler/src/main/java/com/alibaba/android/arouter/compiler/processor/RouteProcessor.java
暂时看不懂怎么回事

**Comment by ooftf** [comment]
还没解决吗？你找一下，所有添加了@Route注解    服务，看看他所实现的接口里面有没有没有继承Iprovider的

**Comment by lu-xu** [comment]
> 还没解决吗？你找一下，所有添加了@route注解 服务，看看他所实现的接口里面有没有没有继承Iprovider的

解决了。解决方案是注释掉所有@Route注解，同时去掉所有Iprovider继承，再运行就报我自己代码的错误，修复完我自己的报错，再把注解都加回来，就ok了。
现在来看，虽然是arouter报的错，但实际上和它没毛线关系，排查方向错了

**Comment by aohanyao** [comment]
给后面的人：我发生这个错误的原因是使用了@route的类报错了，然后Arouter把我的错误吞掉了，最简单的方式是把每个文件都打开看看，是哪里报错了。

**Comment by ycdm** [comment]
上面两楼的方案解决了我的问题。

**Comment by zhi1ong** [comment]
不需要把所有的 Route 注解都注释掉，把 arouter-compiler 依赖注释掉就行

**Comment by HysonHou** [comment]
> > 还没解决吗？你找一下，所有添加了@route注解 服务，看看他所实现的接口里面有没有没有继承Iprovider的
> 
> 解决了。解决方案是注释掉所有@route注解，同时去掉所有Iprovider继承，再运行就报我自己代码的错误，修复完我自己的报错，再把注解都加回来，就ok了。 现在来看，虽然是arouter报的错，但实际上和它没毛线关系，排查方向错了

遇到同样的错,但和这种情况不同,我这边是依赖了不同版本的路由
