### ISSUE TITLE
ARouter在原生Android系统的user版本中，初始化失败

### ISSUE THREAD

**Issue by lilincpp** [alibaba/ARouter#735]
# 背景
应用本身是一个Launcher，使用了ARouter，其运行在在方案商提供的基于原生Android 8.1的Rom之上，并且在userdebug版本中运行测试正常（路由初始化，路由跳转等基础功能），但是在user版本中ARouter初始化会失败.

# 版本信息

系统版本：原生Android 8.1
系统版本类型：userdebug
arouter-api：1.5.0
arouter-compiler：1.2.2

# APK信息

1. apk标记为系统应用，`android:sharedUserId="android.uid.system"`；
2. apk使用原生系统签名；
3. apk标记为一个Launcher，并且开机默认启动；

# 异常信息
```I/ARouter::: ARouter init start.[ ] 
I/ARouter::: Run with debug mode or new install, rebuild router map.[ ] 
I/ARouter::: VM with name 'Android' has multidex support
E/ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths
I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.1][ ] 
E/ARouter: Scan map file in dex files made error.
    java.io.IOException: No original dex files found for dex location /system/app/Ad130SystemJJD/Ad130SystemJJD.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:86)
        at com.alibaba.android.arouter.utils.ClassUtils$1.run(ClassUtils.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
D/ARouter::: Filter 0 classes by packageName <com.alibaba.android.arouter.routes>
I/ARouter::: Find router map finished, map size = 0, cost 24 ms.[ ] 
I/ARouter::: Load root element finished, cost 0 ms.[ ] 
E/ARouter::: No mapping files were found, check your configuration please![ ] 
D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[0], InterceptorIndex[0], ProviderIndex[0][ ] 
I/ARouter::: ARouter init success![ ] 
W/ARouter::: ARouter::There is no route match the path [/arouter/service/interceptor], in group [arouter][ ] `

**Comment by lilincpp** [comment]
# 排查原因

经过验证，发现是Rom在编译的过程中对Apk进行ODEX优化导致Apk中的dex文件不见了（对应的出现了odex文件及vdex文件），因此ARouter找不到dex文件扫描，从而出现异常。

# 解决方法

编译前，在Android.mk文件中禁用ODEX优化，相关代码为：
```
LOCAL_DEX_PREOPT:=false
`
这样编译出来的系统apk就仍然会有dex文件。

**Comment by MoonRune** [comment]
还有个办法就是手动写入路由缓存。

**Comment by MoonRune** [comment]
昨天我也碰到了这个= = 。还有个办法就是手动写入缓存。
