### ISSUE TITLE
ARouter有初始化失败的情况，改怎么解

### ISSUE THREAD

**Issue by lll1590** [alibaba/ARouter#754]
com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Providers$$jymodulevideo]
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5498)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1588)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
     Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Providers$$jymodulevideo]
        at com.alibaba.android.arouter.core.LogisticsCenter.a(LogisticsCenter.java:208)
        at com.alibaba.android.arouter.launcher._ARouter.a(_ARouter.java:61)
        at com.alibaba.android.arouter.launcher.ARouter.a(ARouter.java:41)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1031)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5495)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1588) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6211) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by luqinx** [comment]
所有Providers加一个无参构造函数试试
