### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by iiiSnow** [alibaba/ARouter#820]
项目有两个module，arouter依赖写在子module中，app依赖子module，但是在运行的时候，部分机型必现在dex中找不到AROUTER，无法启动，除非去掉子module中的路由，以下是报错信息
必现机型：Oppo R17  Android9
AROUTER,COMPILE等等都是最新版，kotlin

    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alibaba/android/arouter/launcher/ARouter;
        at com.xx.router.ARouterHelper.init(ARouterHelper.kt:19)
        at com.xx.App.initARouter(App.kt:50)
        at com.xx.business.App.onCreate(App.kt:39)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6376)
        at android.app.ActivityThread.access$1400(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1851)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7279)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alibaba.android.arouter.launcher.ARouter" on path: DexPathList[[zip file "/data/app/com.xx-9m5TtniF5Ldmnsg2YekxCw==/base.apk"],nativeLibraryDirectories=[/data/app/com.xx-9m5TtniF5Ldmnsg2YekxCw==/lib/arm, /data/app/com.xx-9m5TtniF5Ldmnsg2YekxCw==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)

**Comment by LoquatZ** [comment]
- 也遇到了同样的问题，您这解决了么？不知哪位大佬能够解答一下

**Comment by iiiSnow** [comment]
> * 也遇到了同样的问题，您这解决了么？不知哪位大佬能够解答一下
没有 clean build有时候有效

**Comment by LoquatZ** [comment]
> > * d有时候有效
但是这种办法太，随机了阿，太难受了吧

**Comment by LoquatZ** [comment]
> > > 没有clean build有时候有效
> > > 但是这种办法太，随机了阿，太难受了吧

> > > > 我可能找到解决办法了，这个可能跟电脑本地的gradle缓存有关，删除“用户目录”下的.gradle文件夹，然后打开Studio，重新下载，我这是好用的，你可以试试

**Comment by zhangkangbin** [comment]
> > > > 没有clean build有时候有效
> > > > 但是这种办法太，随机了阿，太难受了吧
> 
> > > > > 我可能找到解决办法了，这个可能跟电脑本地的gradle缓存有关，删除“用户目录”下的.gradle文件夹，然后打开Studio，重新下载，我这是好用的，你可以试试

我也是,太随机了，难受，要是多渠道中有一个，岂不gg.

**Comment by iiiSnow** [comment]
> > > > 没有clean build有时候有效
> > > > 但是这种办法太，随机了阿，太难受了吧
> 
> > > > > 我可能找到解决办法了，这个可能跟电脑本地的gradle缓存有关，删除“用户目录”下的.gradle文件夹，然后打开Studio，重新下载，我这是好用的，你可以试试

这个确实是可以的 但是治标不治本啊 根源还没找到

**Comment by LoquatZ** [comment]
> > > > > 没有clean build有时候有效
> > > > > 但是这种办法太，随机了阿，太难受了吧
> > 
> > 
> > > > > > 我可能找到解决办法了，这个可能跟电脑本地的gradle缓存有关，删除“用户目录”下的.gradle文件夹，然后打开Studio，重新下载，我这是好用的，你可以试试
> 
> 这个确实是可以的 但是治标不治本啊 根源还没找到

Arouter不能启动成功的原因，是在Build的时候 "AutowiredProcessor init."没有成功注入，也就是没有执行这个，但是具体原因，还是没有找到，咨询了Arouter官方群也没有给出解释，如果非要找到到底是因为什么，那就可能是AndroidStudio或者gradle的问题。

**Comment by wankey** [comment]
大概率是Android Studio运行时的问题，每次出现这种情况时，我用gradle assembleDebug再编译，就会发现编译出来的包恢复正常了。

Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 8083M
Cores: 16
Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, com.robohorse.robopojogenerator, io.flutter, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, org.intellij.plugins.markdown, pl.charmas.parcelablegenerator

**Comment by iiiSnow** [comment]
> 大概率是Android Studio运行时的问题，每次出现这种情况时，我用gradle assembleDebug再编译，就会发现编译出来的包恢复正常了。
> 
> Android Studio 4.0
> Build #AI-193.6911.18.40.6514223, built on May 20, 2020
> Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.15.5
> GC: ParNew, ConcurrentMarkSweep
> Memory: 8083M
> Cores: 16
> Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
> Non-Bundled Plugins: Dart, org.jetbrains.kotlin, com.robohorse.robopojogenerator, io.flutter, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, org.intellij.plugins.markdown, pl.charmas.parcelablegenerator

可能吧，程序员总有个执念，你AS报错，到底是不是这个错引起的，我怎么解决你

**Comment by zhi1ong** [comment]
感觉是打包环境的问题

**Comment by anaelwu** [comment]
我也遇到了同样的问题，清空.gradle下相关jar包就好使了，但是太难受了，不知道为啥会出现这个原因
