### ISSUE TITLE
测试包没问题，正式包就ARouter init logistics center exception

### ISSUE THREAD

**Issue by zhongdevin** [alibaba/ARouter#825]
Caused by: e.b.a.a.c.a: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Root$$arouterapi]
        at a.a.a.a.c.a(:218)
        at e.b.a.a.e.e.a()
        at com.jingdekeji.yugu.emptyproject.MyApplication.onCreate(:4)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4579)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5280) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by ling9400** [comment]
您好，怎么关闭了呢？  你是怎么解决的？

**Comment by zhongdevin** [comment]
> 您好，怎么关闭了呢？ 你是怎么解决的？

代码混淆问题，你应该搞定了吧

**Comment by ling9400** [comment]
> > 您好，怎么关闭了呢？ 你是怎么解决的？
> 
> 代码混淆问题，你应该搞定了吧
还没有，我就这样配置了混淆还是报错的
`# ARouter
-keep public class com.alibaba.android.arouter.routes.**{*;}
-keep class * implements com.alibaba.android.arouter.facade.template.ISyringe{*;}
-keep interface * implements com.alibaba.android.arouter.facade.template.IProvider`

**Comment by zhongdevin** [comment]
-keep public class com.alibaba.android.arouter.routes.**{*;} -keep public class com.alibaba.android.arouter.facade.**{*;} -keep class * implements com.alibaba.android.arouter.facade.template.ISyringe{*;} # 如果使用了 byType 的方式获取 Service，需添加下面规则，保护接口 -keep interface * implements com.alibaba.android.arouter.facade.template.IProvider # 如果使用了 单类注入，即不定义接口实现 IProvider，需添加下面规则，保护实现 # -keep class * implements com.alibaba.android.arouter.facade.template.IProvider




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/ARouter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月15日(星期三) 上午10:39
收件人:&nbsp;"alibaba/ARouter"<ARouter@noreply.github.com&gt;;
抄送:&nbsp;"小子"<931476839@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/ARouter] 测试包没问题，正式包就ARouter init logistics center exception (#825)





   
您好，怎么关闭了呢？ 你是怎么解决的？
  
代码混淆问题，你应该搞定了吧
 还没有，我就这样配置了混淆还是报错的
 # ARouter -keep public class com.alibaba.android.arouter.routes.**{*;} -keep class * implements com.alibaba.android.arouter.facade.template.ISyringe{*;} -keep interface * implements com.alibaba.android.arouter.facade.template.IProvider
