### ISSUE TITLE
Robolectric测试问题

### ISSUE THREAD

**Issue by xiaozhilaoliu** [alibaba/ARouter#87]
在使用Robolectric做测试的时候,Application中初始化
ARouter.init(this);

错误日志如下:

com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [null]

	at com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:85)
	at com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:61)
	at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41)
	at com.liveaa.education.TestApp.onCreate(TestApp.java:73)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:137)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:290)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:143)

**Comment by zhi1ong** [comment]
不确定你的测试流程是不是有问题，但还是建议你断点调试一下，开放源码的。LogisticsCenter中的异常时在加载路由映射的时候出错了。
