### ISSUE TITLE
快速跳转activity问题

### ISSUE THREAD

**Issue by liujunhongz** [alibaba/ARouter#88]
进入闪屏后快速进入一个activity后再快速进入第二个，第二个会在几秒后destroy掉。
仅在进入应用第一次快速点击出现，后面只要不销毁应用则不重现。

不知道是不是ARouter的问题，但是以前没遇到过这种问题，所以来问问

```
04-20 11:42:22.219 28033-28033/? D/ARouter: Filter 9 classes by packageName <com.alibaba.android.arouter.routes>
04-20 11:42:22.225 28033-28033/? I/ARouter::: ARouter openLog[ ] 
04-20 11:42:22.226 28033-28033/? I/ARouter::: ARouter openDebug[ ] 
04-20 11:42:22.226 28033-28033/? I/ARouter::: ARouter printStackTrace[ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=printStackTrace & LineNumber=145 ] 
04-20 11:42:22.230 28033-28054/? I/ARouter::: ARouter interceptors init over.[ThreadId=3970 & ThreadName=ARouter task pool No.1, thread No.1 & FileName=InterceptorServiceImpl.java & ClassName=com.alibaba.android.arouter.core.InterceptorServiceImpl$3 & MethodName=run & LineNumber=121 ] 
04-20 11:42:28.547 28033-28033/tv.lycam.pclass W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=261 ] 
04-20 11:42:28.549 28033-28033/tv.lycam.pclass W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=261 ] 
04-20 11:42:28.550 28033-28033/tv.lycam.pclass D/ARouter::: The group [Ui] starts loading, trigger by [/Ui/Main][ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=completion & LineNumber=124 ] 
04-20 11:42:28.558 28033-28033/tv.lycam.pclass D/ARouter::: The group [Ui] has already been loaded, trigger by [/Ui/Main][ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=completion & LineNumber=132 ] 
04-20 11:42:28.559 28033-28033/tv.lycam.pclass I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.2][ThreadId=1 & ThreadName=main & FileName=DefaultThreadFactory.java & ClassName=com.alibaba.android.arouter.thread.DefaultThreadFactory & MethodName=newThread & LineNumber=34 ] 
04-20 11:42:30.710 28033-28033/tv.lycam.pclass W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=261 ] 
04-20 11:42:30.711 28033-28033/tv.lycam.pclass W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=261 ] 
04-20 11:42:30.712 28033-28033/tv.lycam.pclass I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.3][ThreadId=1 & ThreadName=main & FileName=DefaultThreadFactory.java & ClassName=com.alibaba.android.arouter.thread.DefaultThreadFactory & MethodName=newThread & LineNumber=34 ] 
04-20 11:42:36.721 28033-28033/tv.lycam.pclass W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=261 ] 
04-20 11:42:36.722 28033-28033/tv.lycam.pclass W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=261 ] 
04-20 11:42:36.723 28033-28033/tv.lycam.pclass I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.4][ThreadId=1 & ThreadName=main & FileName=DefaultThreadFactory.java & ClassName=com.alibaba.android.arouter.thread.DefaultThreadFactory & MethodName=newThread & LineNumber=34 ] 

```

**Comment by liujunhongz** [comment]
另外我添加NavCallback

快速进入ActivityA->ActivityB->ActivityC， 其中ActivityA跳转时执行了mNavFinishCallback

```
NavCallback mNavFinishCallback = new NavCallback() {
        @Override
        public void onArrival(Postcard postcard) {
            finish();
        }

        @Override
        public void onInterrupt(Postcard postcard) {
        }

    };
```
会出现如下情况，上面的情况如果不是快速的进入，等个几秒再进入下一个界面就不会报错
```
04-20 22:20:21.700 14021-14021/tv.lycam.pclass E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: tv.lycam.pclass, PID: 14021
                                                                 java.lang.IllegalArgumentException
                                                                     at android.os.Parcel.readException(Parcel.java:1688)
                                                                     at android.os.Parcel.readException(Parcel.java:1637)
                                                                     at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:5505)
                                                                     at android.app.Activity.isTopOfTask(Activity.java:5978)
                                                                     at android.app.Activity.cancelInputsAndStartExitTransition(Activity.java:4267)
                                                                     at android.app.Activity.startActivityForResult(Activity.java:4244)
                                                                     at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                     at android.app.Activity.startActivity(Activity.java:4518)
                                                                     at android.support.v4.content.ContextCompatJellybean.startActivity(ContextCompatJellybean.java:34)
                                                                     at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:151)
                                                                     at com.alibaba.android.arouter.launcher._ARouter$2.run(_ARouter.java:359)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by zhi1ong** [comment]
应该不是ARouter的问题，ARouter主要是修改了查找Activity这一步，打开Activity的时候和直接startActivity没什么区别

**Comment by liujunhongz** [comment]
你好，谢谢，是项目中RxJava的Observable使用不当，加了跟activity的生命周期绑定就好了
