### ISSUE TITLE
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':xxx:kaptDebugKotlin'.

### ISSUE THREAD

**Issue by LittleNum** [alibaba/ARouter#881]
1.5.0和1.5.1版本的compiler会出现kaptdebugexception，找不到org/apache/commons/collections4/MapUtils这个类，用以前版本的compiler没有问题，不知何故。

Caused by: org.jetbrains.kotlin.kapt3.base.util.KaptBaseError: Exception while annotation processing
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:83)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:34)
        at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)
        ... 22 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections4/MapUtils
        at com.alibaba.android.arouter.compiler.processor.BaseProcessor.init(BaseProcessor.java:51)
        at com.alibaba.android.arouter.compiler.processor.AutowiredProcessor.init(AutowiredProcessor.java:58)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.init(incrementalProcessors.kt:33)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.init(annotationProcessing.kt:170)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:78)
        ... 24 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections4.MapUtils
        ... 37 more

**Comment by zhi1ong** [comment]
断点看看，没有复现，而且 org/apache/commons/collections4/MapUtils 是 arouter-compiler 主动依赖的
