### ISSUE TITLE
每次更新一个版本就一堆报错，kotlin的适配没做好？

### ISSUE THREAD

**Issue by fengxiaocan** [alibaba/ARouter#886]
不是一次两次的了，从1.1.0开始到1.2.1的版本都没问题的，之后每个版本开始更新就报错，搞得很被动，报错了按照文档重新走一遍还是不行。建议做好兼容性。每次更新了哪些属性要贴出来，方法漏一下。

```
注: ARouter::Compiler The user has configuration the module name, it was [app]注: ARouter::Compiler >>> AutowiredProcessor init. <<<注: ARouter::Compiler >>> Found autowired field, start... <<<注: ARouter::Compiler categories finished.错误: ARouter::Compiler An exception is encountered, [null]

at com.alibaba.android.arouter.compiler.processor.AutowiredProcessor.generateHelper(AutowiredProcessor.java:86)
      at com.alibaba.android.arouter.compiler.processor.AutowiredProcessor.process(AutowiredProcessor.java:69)
      at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:89)
      at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:166)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
      at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
      at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:84)
      at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:35)
      at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:179)
      at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
      at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
      at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
      at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
      at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
      at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
      at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
      at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
      at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
      at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
      at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
      at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
      at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
      at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
      at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
      at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
      at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
```

**Comment by fengxiaocan** [comment]
解决办法：不再使用ARouter！

**Comment by zhi1ong** [comment]
开源的东西，代码都放在那里，有什么bug自己调试一下就好了，不要上来就喷。1.5.x 也是很久之前的版本了

**Comment by fengxiaocan** [comment]
1.同一个gradle版本，有时候报错，有时候不会报错，报错的删除了所有缓存,重新走一遍又没事。
2.Java版没有这种错误,kotlin就有。
3.所有的错误指向源码的某个错误，调试起来根本没有这个错误。
4.搜索Github的Issues、百度出来的相关问题，很多相同的问题，解决方案没多少，都没用，也没看见你们做过相关的介绍跟解决方案，每次要解决都是要花几天时间去解决这种问题。
5.使用过很多其他的APT的项目,没有一个出现过这样的错误的。

**Comment by ya939797724** [comment]
？？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/ARouter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月4日(星期一) 下午3:41
收件人:&nbsp;"alibaba/ARouter"<ARouter@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/ARouter] 每次更新一个版本就一堆报错，kotlin的适配没做好？ (#886)





 
开源的东西，代码都放在那里，有什么bug自己调试一下就好了，不要上来就喷。1.5.x 也是很久之前的版本了

**Comment by zhi1ong** [comment]
@fengxiaocan 你描述的这些情况，看不出来是什么问题，我们也没遇到这些问题。代码量也不是很大，有没有问题，到底是什么问题自己翻翻代码就知道了。解决问题之后提交个MR造福他人，才是开源项目的正确用法。
