### ISSUE TITLE
初始化报错

### ISSUE THREAD

**Issue by gongxm0412** [alibaba/ARouter#89]
Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [Failed to open dex files from /data/app/com.hm.daylogapp-1/split_lib_slice_3_apk.apk because: Failure to verify dex file '/data/app/com.hm.daylogapp-1/split_lib_slice_3_apk.apk': Offset(176) should be zero when size is zero for field-ids.]
                                                                      at com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:85)
                                                                      at com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:61)
                                                                      at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41)
                                                                      at com.hm.daylogapp.MainApplication.initARouter(MainApplication.java:25)
                                                                      at com.hm.daylogapp.MainApplication.onCreate(MainApplication.java:16)
                                                                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5659)
                                                                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                      at android.os.Looper.loop(Looper.java:156) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6524) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831) 

我初始化的代码是放在Application里面
```
 private void initARouter() {
        if (BuildConfig.DEBUG) {
            ARouter.openLog();     // 打印日志
            ARouter.openDebug();   // 开启调试模式(如果在InstantRun模式下运行，必须开启调试模式！线上版本需要关闭,否则有安全风险)
        }
        ARouter.init(this);
    }
```

**Comment by zhi1ong** [comment]
Instant Run的问题，看起来是手机的兼容性问题，是真机还是虚拟机，手机型号报一下，上线之后不会有这个问题，InstantRun只是作用于开发的

**Comment by gmfbilu** [comment]
大哥，你解决了吗，我关闭了instant run还是和你一样的错误
