### ISSUE TITLE
初始化崩溃    线上一个用户，其他用户正常   

### ISSUE THREAD

**Issue by TianRC** [alibaba/ARouter#894]
Arouter 版本 1.5.1

java.lang.ClassNotFoundException	com.vivo.wallet.safelock.service.SafeLockDataService
ARouter$$Providers$$lib_safe_lock.java	16
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/vivo/wallet/safelock/service/SafeLockDataService;
	at com.alibaba.android.arouter.routes.ARouter$$Providers$$lib_safe_lock.loadInto(ARouter$$Providers$$lib_safe_lock.java:16)
	at com.alibaba.android.arouter.core.LogisticsCenter.registerProvider(LogisticsCenter.java:134)
	at com.alibaba.android.arouter.core.LogisticsCenter.register(LogisticsCenter.java:86)
	at com.alibaba.android.arouter.core.LogisticsCenter.loadRouterMap(LogisticsCenter.java:69)
	at com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:160)
	at com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:59)
	at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41)
	at com.vivo.wallet.O0000O0o.O000000o(VivoWalletAppHelper.java:87)
	at com.vivo.wallet.VivoWalletApp.onCreate(VivoWalletApp.java:57)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6832)
	at android.app.ActivityThread.access$1600(ActivityThread.java:255)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2082)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:230)
	at android.app.ActivityThread.main(ActivityThread.java:7762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: java.lang.ClassNotFoundException: com.vivo.wallet.safelock.service.SafeLockDataService
	... 19 more

**Comment by TianRC** [comment]
Arouter 版本 1.5.1

**Comment by zhi1ong** [comment]
看起来和 ARouter 关系不大
