### ISSUE TITLE
在AndroidX 上面会报错

### ISSUE THREAD

**Issue by CNHTT** [alibaba/ARouter#926]
## Look at here

在AndroidX 上使用面会报错

```


> Task :module_main:kaptDebugKotlin FAILED
注: ARouter::Compiler The user has configuration the module name, it was [module_main]注: ARouter::Compiler >>> AutowiredProcessor init. <<<注: ARouter::Compiler The user has configuration the module name, it was [module_main]注: ARouter::Compiler >>> InterceptorProcessor init. <<<注: ARouter::Compiler The user has configuration the module name, it was [module_main]注: ARouter::Compiler >>> RouteProcessor init. <<<注: ARouter::Compiler >>> Found routes, start... <<<注: ARouter::Compiler >>> Found routes, size is 1 <<<错误: ARouter::Compiler An exception is encountered, [null]
      at com.alibaba.android.arouter.compiler.processor.RouteProcessor.parseRoutes(RouteProcessor.java:135)
      at com.alibaba.android.arouter.compiler.processor.RouteProcessor.process(RouteProcessor.java:113)
      at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
      at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:166)
      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)
      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)
      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1334)
      at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
      at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:81)
      at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:31)
      at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
      at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:232)
      at org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction.execute(KaptWithoutKotlincTask.kt:198)
      at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
      at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
      at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
      at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
      at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
      at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
      at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
      at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
      at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
      at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
      at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
      at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
      at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
      at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
      at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
      at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
      at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
      at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
      at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
      at java.base/java.lang.Thread.run(Thread.java:834)
> Task :app:dataBindingMergeGenClassesDebug UP-TO-DATE
```

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by CNHTT** [comment]
public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    
    会报错 在Androidx 上   麻烦修改 提供下 Android X 版本 引用包 谢谢

**Comment by gudao20080** [comment]
我的AndroidX也不行，光是合并Manifest文件就报错了
![image](https://user-images.githubusercontent.com/6431152/122858554-08e37900-d34d-11eb-990d-2024b71ea4da.png)
加了tools:也不行

**Comment by wufuqi123** [comment]
我也是使用androidX报错
最开始是依赖冲突，然后我去除冲突的依赖
![image](https://user-images.githubusercontent.com/23232556/124246390-76648600-db53-11eb-87bd-32ec889716b1.png)
![image](https://user-images.githubusercontent.com/23232556/124246410-79f80d00-db53-11eb-9e84-2ff326e00173.png)


去除依赖后，当进行跳转时，报错 Failed resolution of: Landroid/support/v4/app/ActivityCompat;
![image](https://user-images.githubusercontent.com/23232556/124246598-a6ac2480-db53-11eb-9747-0c5b4a77ca7e.png)
![image](https://user-images.githubusercontent.com/23232556/124246627-ac096f00-db53-11eb-8da1-5f4fe0e6d028.png)

**Comment by wufuqi123** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/ActivityCompat;
        at com.alibaba.android.arouter.launcher._ARouter.startActivity(_ARouter.java:429)
        at com.alibaba.android.arouter.launcher._ARouter.access$200(_ARouter.java:44)
        at com.alibaba.android.arouter.launcher._ARouter$3.run(_ARouter.java:372)
        at com.alibaba.android.arouter.launcher._ARouter.runInMainThread(_ARouter.java:413)
        at com.alibaba.android.arouter.launcher._ARouter._navigation(_ARouter.java:369)
        at com.alibaba.android.arouter.launcher._ARouter.access$100(_ARouter.java:44)
        at com.alibaba.android.arouter.launcher._ARouter$2.onContinue(_ARouter.java:321)
        at com.alibaba.android.arouter.core.InterceptorServiceImpl.doInterceptions(InterceptorServiceImpl.java:63)
        at com.alibaba.android.arouter.launcher._ARouter.navigation(_ARouter.java:313)
        at com.alibaba.android.arouter.launcher.ARouter.navigation(ARouter.java:184)
        at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:146)
        at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:137)
        at com.alibaba.android.arouter.facade.Postcard.navigation(Postcard.java:128)
        at com.chuangyi.yike.data.MainActivityData.jump(MainActivityData.kt:9)
        at com.chuangyi.yike.databinding.ActivityMainBindingImpl._internalCallbackOnClick(ActivityMainBindingImpl.java:158)
        at com.chuangyi.yike.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:7125)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by wufuqi123** [comment]
[https://github.com/alibaba/ARouter/issues/938](url)   解决了我的androidx   报错问题

**Comment by appdev** [comment]
去年就 Android X 了  ，没有任何问题

**Comment by akingyin1987** [comment]
android.enableJetifier=true 只能打这个打开

**Comment by zhi1ong** [comment]
AndroidX 下 support-v4/Jetifier 兼容问题已由 #785 统一跟踪。本 issue 中的过渡方案仍是启用 `android.enableJetifier=true`，原生迁移在主 issue 处理。
