### ISSUE TITLE
android.util.AndroidRuntimeException: FORWARD_RESULT_FLAG used while also requesting a result  arouter_api=1.5.2  arouter_compiler=1.5.2

### ISSUE THREAD

**Issue by zzlandroid** [alibaba/ARouter#955]
麻烦看下这个问题,必现的 跳转页面出现
 09-02 17:20:56.377717 16838 16838 E AndroidRuntime: android.util.AndroidRuntimeException: FORWARD_RESULT_FLAG used while also requesting a result
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2074)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5343)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at com.alibaba.android.arouter.b.b.a(_ARouter.java:444)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at com.alibaba.android.arouter.b.b.a(_ARouter.java:45)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at com.alibaba.android.arouter.b.b$3.run(_ARouter.java:391)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:238)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7823)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1017)
09-02 17:20:56.377717 16838 16838 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1017)

**Comment by zhi1ong** [comment]
该异常由 Android framework 在同时使用 `FLAG_ACTIVITY_FORWARD_RESULT` 和非负 `requestCode` 请求结果时直接抛出。当前信息还无法确认这个 flag 是由调用方、来源 Activity 的 Intent，还是 ARouter 调用链带入。

请补充完整导航代码（包括 `navigation(activity, requestCode)`）、所有 `withFlags` / Intent flags、来源 Activity 的 Intent flags、设备/系统版本，并提供最小复现工程。临时规避方式是二选一：移除 `FLAG_ACTIVITY_FORWARD_RESULT`，或不要以 requestCode 请求结果。

该 issue 保持打开并标记为 `needs-repro`；复现后再决定 ARouter 是否应在 API 层拒绝或清理这组冲突参数。

**Comment by zhi1ong** [comment]
develop 已处理请求结果时 FLAG_ACTIVITY_FORWARD_RESULT 与 requestCode 的冲突，结果回传回归通过。尚未发布，先关闭此问题。
