### ISSUE TITLE
Arouter严格模式报错

### ISSUE THREAD

**Issue by gzsword** [alibaba/ARouter#97]
'''java
05-04 17:49:56.524 23565-23574/com.midea.mission.test E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                    java.lang.Throwable: Explicit termination method 'close' not called
                                                                        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                        at dalvik.system.DexFile.<init>(DexFile.java:116)
                                                                        at dalvik.system.DexFile.<init>(DexFile.java:99)
                                                                        at com.alibaba.android.arouter.utils.ClassUtils.getFileNameByPackageName(ClassUtils.java:64)
                                                                        at com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:61)
                                                                        at com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:58)
                                                                        at com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41)
                                                                        at com.midea.ConnectApplication.onCreate(ConnectApplication.java:209)
                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5659)
                                                                        at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                        at android.os.Looper.loop(Looper.java:156)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
'''

严格模式报这个错误，请问如何修复？
com.alibaba:arouter-api:1.0.7
com.alibaba:arouter-compiler:1.0.3

**Comment by zhi1ong** [comment]
感谢反馈，该问题会在后续版本中修复，建议
 
1. 优先使用arouter最新版本
2. 暂时忽略该错误，不影响使用

**Comment by gzsword** [comment]
"arouter-api"                 : "com.alibaba:arouter-api:1.2.1.1",
            "arouter-compiler"            : "com.alibaba:arouter-compiler:1.1.2.1",

更新到最新的版本还是会存在这个问题

**Comment by zhi1ong** [comment]
dev代码修复了，但是一直没发布，这块暂时先忽略掉
