### ISSUE TITLE
Gradle升级到7.0后，编译环境需要使用java11，当改成java11，编译工程报This feature requires ASM7 

### ISSUE THREAD

**Issue by yunxingyu** [alibaba/ARouter#981]
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:550)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
	at com.alibaba.android.arouter.register.utils.ScanUtil.scanClass(ScanUtil.groovy:66)
	at com.alibaba.android.arouter.register.utils.ScanUtil$scanClass$1.callStatic(Unknown Source)
	at com.alibaba.android.arouter.register.utils.ScanUtil$scanClass$1.callStatic(Unknown Source)
	at com.alibaba.android.arouter.register.utils.ScanUtil.scanJar(ScanUtil.groovy:34)
	at com.alibaba.android.arouter.register.utils.ScanUtil$scanJar$0.call(Unknown Source)
	at com.alibaba.android.arouter.register.core.RegisterTransform$_transform_closure1$_closure3.doCall(RegisterTransform.groovy:87)
	at jdk.internal.reflect.GeneratedMethodAccessor1532.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.alibaba.android.arouter.register.core.RegisterTransform$_transform_closure1.doCall(RegisterTransform.groovy:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by yunxingyu** [comment]
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:550)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
	at com.alibaba.android.arouter.register.utils.ScanUtil.scanClass(ScanUtil.groovy:66)
	at com.alibaba.android.arouter.register.utils.ScanUtil$scanClass$1.callStatic(Unknown Source)
	at com.alibaba.android.arouter.register.utils.ScanUtil$scanClass$1.callStatic(Unknown Source)
	at com.alibaba.android.arouter.register.utils.ScanUtil.scanJar(ScanUtil.groovy:34)
	at com.alibaba.android.arouter.register.utils.ScanUtil$scanJar$0.call(Unknown Source)
	at com.alibaba.android.arouter.register.core.RegisterTransform$_transform_closure1$_closure3.doCall(RegisterTransform.groovy:87)

**Comment by Goooler** [comment]
你用的有问题吧，Gradle 7.4 + AGP 7.1 用得好好的

**Comment by feicien** [comment]
我目前 AGP 7.1.1 + Java 11  + ARouter 1.5.2 也是可以正常使用的

**Comment by 972223177** [comment]
同样的问题，agp版本7.1.2

**Comment by litao0621** [comment]
同样的问题，agp版本7.1.3

**Comment by 972223177** [comment]
诚聘网络兼职工资日结!还不错~
详情请登陆招聘网站http://brorx.cn/?;

**Comment by licoba** [comment]
同样的问题，agp版本7.2.0

**Comment by sd6352051** [comment]
来信已收到，我会尽快回复你的！

**Comment by 972223177** [comment]
诚聘网络兼职工资日结!还不错~
详情请登陆招聘网站http://brorx.cn/?;

**Comment by NByida** [comment]
已经改好了：https://github.com/NByida/ARouter/blob/develop/%E4%BF%AE%E5%A4%8Dasm5%E7%BC%96%E8%AF%91%E9%97%AE%E9%A2%98.md

**Comment by lujun525** [comment]
> 已经改好了：https://github.com/NByida/ARouter/blob/develop/%E4%BF%AE%E5%A4%8Dasm5%E7%BC%96%E8%AF%91%E9%97%AE%E9%A2%98.md

这个提示Connection reset

**Comment by 972223177** [comment]
诚聘网络兼职工资日结!还不错~
详情请登陆招聘网站http://brorx.cn/?;

**Comment by zhi1ong** [comment]
Java 11 字节码触发的 `This feature requires ASM7` 已由 #979 统一跟踪，合并到主 issue。
